# Generated by Django 5.0.7 on 2024-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0003_register_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register_model",
            name="cpassw",
        ),
        migrations.AddField(
            model_name="register_model",
            name="about",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="dob",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register_model",
            name="phoneno",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
