# Generated by Django 5.0.7 on 2024-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthcareapp",
            "0004_remove_register_model_cpassw_register_model_about_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="dob",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
