# Generated by Django 5.0.7 on 2024-08-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0007_register_model_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register_model",
            name="about",
        ),
        migrations.RemoveField(
            model_name="register_model",
            name="address",
        ),
        migrations.RemoveField(
            model_name="register_model",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="register_model",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="register_model",
            name="pincode",
        ),
    ]
