# Generated by Django 5.0.7 on 2024-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0008_remove_register_model_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="about",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="dob",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="register_model",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
