# Generated by Django 5.0.7 on 2024-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0011_register_model_address_register_model_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="cpassw",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
