# Generated by Django 5.0.7 on 2024-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0012_register_model_cpassw"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="image_ed",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
