# Generated by Django 5.0.7 on 2024-09-03 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0013_register_model_image_ed"),
    ]

    operations = [
        migrations.CreateModel(
            name="drug_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", ckeditor.fields.RichTextField()),
                ("uses_drug", ckeditor.fields.RichTextField()),
                ("sideeffects_drug", ckeditor.fields.RichTextField()),
                ("warning_drug", ckeditor.fields.RichTextField()),
                ("precaution_drug", ckeditor.fields.RichTextField()),
                ("interactions_Drug", ckeditor.fields.RichTextField()),
                ("overdose_drug", ckeditor.fields.RichTextField()),
                (
                    "imgmain_Drug",
                    models.ImageField(blank=True, null=True, upload_to="data"),
                ),
                ("color_Drug", ckeditor.fields.RichTextField()),
                ("shape_Drug", ckeditor.fields.RichTextField()),
                ("imprint_Drug", ckeditor.fields.RichTextField()),
                ("drug_title", ckeditor.fields.RichTextField()),
                ("imags_drug", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
