# Generated by Django 5.0.7 on 2024-09-04 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0014_drug_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_model",
            name="color_Drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="drug_title",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="imags_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="imprint_Drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="interactions_Drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="overdose_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="precaution_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="shape_Drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="sideeffects_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="uses_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug_model",
            name="warning_drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
