# Generated by Django 5.0.7 on 2024-09-04 13:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0015_alter_drug_model_color_drug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug_model",
            name="genericname",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
