# Generated by Django 5.0.7 on 2024-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0016_drug_model_genericname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_model",
            name="drug_name",
            field=models.CharField(max_length=200),
        ),
    ]
