# Generated by Django 5.0.7 on 2024-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0017_alter_drug_model_drug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_model",
            name="genericname",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
