# Generated by Django 5.0.7 on 2024-09-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0018_alter_drug_model_genericname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_model",
            name="genericname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
