# Generated by Django 5.0.7 on 2024-09-06 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0019_alter_drug_model_genericname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug_model",
            name="imgmain_Drug",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
