# Generated by Django 5.0.7 on 2024-09-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0024_bodypart_symptom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("symptoms", models.ManyToManyField(to="healthcareapp.symptom")),
            ],
        ),
    ]
