# Generated by Django 5.0.7 on 2024-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0026_blogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imprint",
                    models.CharField(
                        help_text="Text or symbols imprinted on the pill",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(help_text="Color of the pill", max_length=50),
                ),
                (
                    "shape",
                    models.CharField(help_text="Shape of the pill", max_length=50),
                ),
                (
                    "rxcui",
                    models.CharField(
                        blank=True,
                        help_text="RxNorm Concept Unique Identifier",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Drug name", max_length=100, null=True
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        help_text="Strength of the pill",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL to an image of the pill", null=True
                    ),
                ),
            ],
        ),
    ]
