# Generated by Django 5.0.7 on 2024-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0027_pill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pill",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="pill",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="pill",
            name="rxcui",
        ),
        migrations.AddField(
            model_name="pill",
            name="image_urls",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
