# Generated by Django 5.0.7 on 2024-11-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0029_register_model_google_auth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register_model",
            name="google_auth",
        ),
    ]
