# Generated by Django 5.0.7 on 2024-11-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0030_remove_register_model_google_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="cpassw",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="register_model",
            name="passw",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
