# Generated by Django 5.0.7 on 2024-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcareapp", "0031_alter_register_model_cpassw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="cpassw",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="register_model",
            name="passw",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
